### ISSUE TITLE
No clear way to modify .editorconfig for dfmt

### ISSUE THREAD

**Issue by Rock48** [dlang-vscode/dlang-vscode#14]
I can't find a clear way to modify the .editorconfig used when formatting, this is important to me as I much prefer the `otbs` brace style.

**Comment by LaurentTreguier** [comment]
Don't worry, configuration for DCD and dfmt has been added in #11. There has been no extension release since then, but hopefully it's a matter of time before it gets shipped. 
Alternatively, you can also get and build the master version of the extension to make use of it right now. All dfmt formatting options are mapped to `d.dfmt.*` in the extension configuration. 
Using otbs is the one reason I actually thought about making dfmt configurable :smile:

**Comment by mattiascibien** [comment]
My bad. I still need to test it on my macchine and I did not have much time lately. 0.8.0 is on the way, I swear.

**Comment by LaurentTreguier** [comment]
@mattiascibien no problem, as long as it's done at some point, it's all good

**Comment by Rock48** [comment]
Fantastic :D

I'll see if I can compile it, but I can wait for the next release.

**Comment by LaurentTreguier** [comment]
```
npm install
vsce package
code dlang-0.7.0.vsix
```

This should be enough to install the extension manually I think

**Comment by mattiascibien** [comment]
I am going to setup appveyor it builds and packages the extension automatically.

**Comment by Rock48** [comment]
Sweet :>. On an unrelated note, I can't get the debug extension to work at
all. It just says `Debug adapter process has terminated unexpectedly` Is
there any special configuration I need to do?

**Comment by LaurentTreguier** [comment]
@Rock48 looks a lot like [this](https://github.com/WebFreak001/code-debug/issues/61)
