### ISSUE TITLE
SDL Syntax Highlighting

### ISSUE THREAD

**Issue by mattiascibien** [dlang-vscode/dlang-vscode#15]
As the sublime text package has support for SDL and is relying on a tmLanguage file I suggest to import it and make it available on our plugin.

Source: https://github.com/s-ludwig/sublime-sdlang

**Comment by LaurentTreguier** [comment]
I had done a simple syntax highlighting for [SDL](https://github.com/LaurentTreguier/sdlang-vscode). I don't know how good it is compared to the one from the sublime text package though. 
I think it's better to keep it as a separate extension since it's not exclusively for D (even though I have yet to see it used elsewhere). 
Maybe an extension dependency would do the trick?

**Comment by mattiascibien** [comment]
@LaurentTreguier will have a look. In any case we have the blessing from the author: https://github.com/s-ludwig/sublime-sdlang/issues/2#issuecomment-244943559

EDIT: sorry I missed your project, did not know about that. I will look into adding it as a dependency
