### ISSUE TITLE
Version 0.8.1

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-vscode/dlang-vscode#17]
@mattiascibien With [this commit](https://github.com/dlang-vscode/dlang-vscode/commit/4a9e56331a587ad30e9eded3dcd93b11cee9200e), a nasty bug has been resolved : DCD would try to use a system wide DCD installation instead of the one provided by dub ; which means the extension currently crashes whenever DCD is not installed globally...
I think there should be a 0.8.1 bugfix release on the VSCode marketplace.

**Comment by mattiascibien** [comment]
Hello,
Unforunately i do not have access to a computer with vscode installed. I will push the release on monday

Il 23 ott 2016 11:15, LaurentTreguier notifications@github.com ha scritto:

@mattiascibienhttps://github.com/mattiascibien With this commithttps://github.com/dlang-vscode/dlang-vscode/commit/4a9e56331a587ad30e9eded3dcd93b11cee9200e, a nasty bug has been resolved : DCD would try to use a system wide DCD installation instead of the one provided by dub ; which means the extension currently crashes whenever DCD is not installed globally...
I think there should be a 0.8.1 bugfix release on the VSCode marketplace.

**Comment by mattiascibien** [comment]
Hi.
I am trying to push this online today. Sorry for the wait.

**Comment by LaurentTreguier** [comment]
@mattiascibien No problem

**Comment by mattiascibien** [comment]
@LaurentTreguier http://wiki.dlang.org/Editors seems this is the second most complete editor for D. Nice work Laurent.

**Comment by LaurentTreguier** [comment]
@mattiascibien Well thanks :smile:

**Comment by mattiascibien** [comment]
And we are online 👍
