### ISSUE TITLE
DUB Commands

### ISSUE THREAD

**Issue by mattiascibien** [dlang-vscode/dlang-vscode#3]
Add support for DUB commands like `dub run`, `dub compile`, `dub test` and so on.

**Comment by mattiascibien** [comment]
@LaurentTreguier started working on something in the branch [dub-commands](https://github.com/mattiascibien/dlang-vscode/tree/dub-commands).

**Comment by LaurentTreguier** [comment]
I've experimented something with some dub commands. For now there is now API to provide VSCode with a default tasks.json file, but it's still easy to directly write contents to the file with a single command. This way commands like `dub build` or `dub run` can be tasks instead of VSCode commands. The `dub build` and `dub test` commands can even be linked to VSCode's build/test commands and keyboard shortcuts.
