### ISSUE TITLE
DUB configuration specification from the status bar is missing

### ISSUE THREAD

**Issue by 9il** [dlang-vscode/dlang-vscode#44]

**Comment by LaurentTreguier** [comment]
Can you tell more details about this issue ?

Is it randomly happening or is there a way to reproduce this ?

**Comment by 9il** [comment]
There build types and build configurations.
http://code.dlang.org/package-format?lang=json#configurations
Configurations requires to parse dub.json/dub.sdl

**Comment by LaurentTreguier** [comment]
Oh I see, I mixed up build types and configurations. It sure will be nice to have configurations on the status bar as well.

**Comment by 9il** [comment]
Thanks! Would you make the first 2017 year release?

**Comment by LaurentTreguier** [comment]
It's true that there has been some time since the `0.9.0` release now...
@mattiascibien Do you think you could publish a new version on the marketplace ? Or should we finish work with the `testing` branch first ?

**Comment by mattiascibien** [comment]
I guess it could be possible. I am a bit busy at the moment but I am going to, definitely.


________________________________
Da: LaurentTreguier <notifications@github.com>
Inviato: domenica 4 giugno 2017 17:40
A: dlang-vscode/dlang-vscode
Cc: Mattias Cibien; Mention
Oggetto: Re: [dlang-vscode/dlang-vscode] DUB configuration specification from the status bar is missing (#44)


It's true that there has been some time since the 0.9.0 release now...
@mattiascibien<https://github.com/mattiascibien> Do you think you could publish a new version on the marketplace ? Or should we finish work with the testing branch first ?
