### ISSUE TITLE
UDA highlighting

### ISSUE THREAD

**Issue by sysint64** [dlang-vscode/dlang-vscode#46]
the UDA is not highlighted examples:
```D
@Field bool resizable = true;
@ViewWidget Button okButton;

@OnClickListener("okButton")
void onOkButtonClick(Widget widget) {
    ...
}
```

**Comment by LaurentTreguier** [comment]
Syntax highlighting comes from [this textmate bundle](https://github.com/textmate/d.tmbundle), which indeed does not highlight UDA's. I think we should write our own syntax file for this extension at some point, since there are some missing features right now, and the latest changes from the textmate bundle even break some stuff.

**Comment by sysint64** [comment]
@LaurentTreguier 
>  think we should write our own syntax file for this extension at some point

I added UDA support by modifying the regex in `d.tmLanguage`, now UDAs highlights correctly...

**Comment by LaurentTreguier** [comment]
That's great then ! Can you make a pull request to both this extension and the  textmate bundle, or share the change here to integrate it ?

**Comment by sysint64** [comment]
@LaurentTreguier ok no problems

**Comment by sysint64** [comment]
#47
