### ISSUE TITLE
Code Assist From dub Packages?

### ISSUE THREAD

**Issue by TritiatedWater** [dlang-vscode/dlang-vscode#51]

**Comment by LaurentTreguier** [comment]
I thought the current released extension supported code assist from dub packages... What package are you trying to use ?

**Comment by TritiatedWater** [comment]
I'm using [Godot-D](http://code.dlang.org/packages/godot-d). The code assist only helps if I  already typed a method.
Eg: When printing a message `print("Hello");` for the first time, code assist does not help, after that it only list the method but without it's description.

**Comment by LaurentTreguier** [comment]
What OS are you using ? I'm noticing DCD is giving me trouble on Windows. A lot of changes have happened in the repo since the last release on the marketplace though, maybe using the latest code would help ? I'm not really confident about that, but as far as I know it could still be better overall compared to using the extension from the marketplace.
Here is a build from : [dlang-0.10.0.vsix.zip](https://github.com/dlang-vscode/dlang-vscode/files/1833163/dlang-0.10.0.vsix.zip)
You can also build it yourself with :
```shell
git clone https://github.com/dlang-vscode/dlang-vscode
cd dlang-vscode
npm install
./node_modules/.bin/vsce package
```
If this doesn't work, have you tried https://marketplace.visualstudio.com/items?itemName=webfreak.code-d-beta ? This isn't solving the problem, but this extension has seen more work lately and maybe it would work out better for you.

**Comment by TritiatedWater** [comment]
That recent build fixed the problem.
Although the description sometimes only list the method's paramater.
